[target.'cfg(target_os = "none")']
runner = "cargo run --package os-runner --release --"

[alias]
kbuild = "build --target x86_64-kernel.json -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-kernel.json -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-kernel.json -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"
